version: '3'
volumes:
  data:
  export:
services:
  postgres:
    image: docker.io/postgres:latest
    container_name: racoon-filesystem-checker-postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - data:/var/lib/postgresql/data
      - export:/export
