version: '3'
volumes:
  data:
  export:
services:
  postgres:
    image: docker.io/postgres:latest
    container_name: racoon-filesystem-checker-postgres
    expose:
      - '54321'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=racoon-filesystem-checker
    volumes:
      - data:/var/lib/postgresql/data
      - export:/export
  racoon-filesystem-checker-1:
    image: docker.io/savanyaj/racoon-filesystem-checker:main
    container_name: racoon-filesystem-checker-backend1
    expose:
      - '8081'
    environment:
      - DB_URL=postgresql://postgres:5432/racoon-filesystem-checker
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8081
      - APP_USER=App1
    ports:
      - '8081:8081'
  racoon-filesystem-checker-2:
    image: docker.io/savanyaj/racoon-filesystem-checker:main
    container_name: racoon-filesystem-checker-backend2
    expose:
      - '8082'
    environment:
      - DB_URL=postgresql://postgres:5432/racoon-filesystem-checker
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8082
      - APP_USER=App2
    ports:
      - '8082:8082'