name: Racoon-Filesystem-checker CI pipeline

on:
  pull_request:
    branches: [ "main" ]

jobs:
  checkout:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4

    - name: Set up Java JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build and Test with Gradle
      run: ./gradlew build

  sonarqube:
    name: SonarQube code analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master
      with:
        scanMetadataReportFile: build/sonar/report-task.txt
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        
    - name: "SonarQube Quality Gate Status"
      run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
  
    
    


    

          
